# Generated by Django 5.2.11 on 2026-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_vendor',
            field=models.BooleanField(default=False, verbose_name='Is Seller'),
        ),
    ]
